[(<class 'tensorflow.python.framework.errors_impl.UnknownError'>, UnknownError(), <traceback object at 0x7faaf0142100>), (<class 'tensorflow.python.framework.errors_impl.UnknownError'>, UnknownError(), <traceback object at 0x7faa9c68de00>), (<class 'tensorflow.python.framework.errors_impl.UnknownError'>, UnknownError(), <traceback object at 0x7faa8055bb80>)]